# see also: https://github.com/dustin10/VichUploaderBundle/blob/master/docs/usage.md
vich_uploader:
    db_driver: orm

    mappings:
        media_object:
            uri_prefix: /media
            upload_destination: '%kernel.project_dir%/public/media'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: App\Naming\OrignameNamer
            delete_on_remove: true