INSERT INTO
ingredient (`name`, `season_start`, `season_end`)
VALUES
('Artischocke', '6', '8'),
('Aubergine', '5', '9'),
('Blumenkohl', '4', '10'),
('Dicke Bohnen', '5', '7'),
('Grüne Bohnen', '5', '9'),
('Brokkoli', '5', '10'),
('Erbsen', '5', '7'),
('Fenchel', '5', '9'),
('Frühlingszwiebeln', '4', '9'),
('Grünkohl', '9', '0'),
('Knollensellerie', '5', '11'),
('Kohlrabi', '4', '9'),
('Kürbis', '7', '10'),
('Mairübchen', '4', '6'),
('Mais', '6', '9'),
('Mangold', '4', '9'),
('Meerettich', '9', '0'),
('Karotten', '6', '10'),
('Pak Choi', '4', '9'),
('Paprikaschote', '5', '9'),
('Pastinaken', '10', '0'),
('Petersilienwurzel', '10', '0'),
('Pfifferlinge', '6', '9'),
('Lauch', '7', '11'),
('Radieschen', '3', '9'),
('Rettich', '4', '10'),
('Romanesco', '4', '9'),
('Rote Bete', '9', '0'),
('Blaukraut', '4', '10'),
('Gurke', '4', '7'),
('Spargel', '3', '5'),
('Spinat', '3', '9'),
('Spitzkohl', '4', '9'),
('Staudensellerie', '5', '9'),
('Steckrübe', '10', '1'),
('Steinpilz', '7', '9'),
('Süßkartoffel', '8', '9'),
('Tomate', '6', '8'),
('Weißkohl', '8', '10'),
('Wirsing', '5', '1'),
('Zucchini', '5', '8'),
('Zuckerschoten', '4', '5'),
('Äpfel', '7', '9'),
('Aprikosen', '6', '7'),
('Birnen', '6', '9'),
('Brombeeren', '6', '8'),
('Erdbeeren', '4', '6'),
('Haselnüsse', '8', '9'),
('Heidelbeeren', '5', '8'),
('Himbeeren', '5', '8'),
('Kirschen', '5', '7'),
('Maronen', '8', '11'),
('Nektarinen', '6', '8'),
('Pfirsiche', '6', '8'),
('Pflaumen', '5', '8'),
('Quitten', '9', '10'),
('Rhabarber', '2', '7'),
('Walnüsse', '8', '9'),
('Weintrauben', '8', '9'),
('Zwetschgen', '5', '8'),
('Bärlauch', '2', '4'),
('Basilikum', '5', '9'),
('Chicoree', '9', '3'),
('Dill', '4', '9'),
('Feldsalat', '9', '2'),
('Minze', '4', '9'),
('Radicchio', '5', '9'),
('Rucola', '2', '10'),
('Salbei', '4', '7'),
('Schnittlauch', '2', '8');