/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Cookup
 * @export
 * @interface Cookup
 */
export interface Cookup {
    /**
     * 
     * @type {number}
     * @memberof Cookup
     */
    'cookupId'?: number;
    /**
     * 
     * @type {string}
     * @memberof Cookup
     */
    'user'?: string;
    /**
     * 
     * @type {string}
     * @memberof Cookup
     */
    'recipe'?: string;
    /**
     * 
     * @type {string}
     * @memberof Cookup
     */
    'date'?: string;
}

