/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * IngredientCategory
 * @export
 * @interface IngredientCategory
 */
export interface IngredientCategory {
    /**
     * 
     * @type {number}
     * @memberof IngredientCategory
     */
    'categoryId'?: number;
    /**
     * 
     * @type {string}
     * @memberof IngredientCategory
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof IngredientCategory
     */
    'order'?: number;
}

