/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Ingredient
 * @export
 * @interface Ingredient
 */
export interface Ingredient {
    /**
     * 
     * @type {number}
     * @memberof Ingredient
     */
    'ingredientId'?: number;
    /**
     * 
     * @type {string}
     * @memberof Ingredient
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof Ingredient
     */
    'seasonStart'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Ingredient
     */
    'seasonEnd'?: number | null;
}

