/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { InlineResponse200HydraSearchHydraMapping } from './inline-response200-hydra-search-hydra-mapping';

/**
 * 
 * @export
 * @interface InlineResponse200HydraSearch
 */
export interface InlineResponse200HydraSearch {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200HydraSearch
     */
    '@type'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200HydraSearch
     */
    'hydra:template'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200HydraSearch
     */
    'hydra:variableRepresentation'?: string;
    /**
     * 
     * @type {Array<InlineResponse200HydraSearchHydraMapping>}
     * @memberof InlineResponse200HydraSearch
     */
    'hydra:mapping'?: Array<InlineResponse200HydraSearchHydraMapping>;
}

