/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineResponse200HydraSearchHydraMapping
 */
export interface InlineResponse200HydraSearchHydraMapping {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200HydraSearchHydraMapping
     */
    '@type'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200HydraSearchHydraMapping
     */
    'variable'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200HydraSearchHydraMapping
     */
    'property'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse200HydraSearchHydraMapping
     */
    'required'?: boolean;
}

