/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MediaObjectJsonldMediaObjectRead
 */
export interface MediaObjectJsonldMediaObjectRead {
    /**
     * 
     * @type {string}
     * @memberof MediaObjectJsonldMediaObjectRead
     */
    '@id'?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaObjectJsonldMediaObjectRead
     */
    '@type'?: string;
    /**
     * 
     * @type {string | any}
     * @memberof MediaObjectJsonldMediaObjectRead
     */
    '@context'?: string | any;
    /**
     * 
     * @type {string}
     * @memberof MediaObjectJsonldMediaObjectRead
     */
    'contentUrl'?: string | null;
}

