/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RecipeIngredientJsonld
 */
export interface RecipeIngredientJsonld {
    /**
     * 
     * @type {string | any}
     * @memberof RecipeIngredientJsonld
     */
    '@context'?: string | any;
    /**
     * 
     * @type {string}
     * @memberof RecipeIngredientJsonld
     */
    '@id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeIngredientJsonld
     */
    '@type'?: string;
    /**
     * 
     * @type {number}
     * @memberof RecipeIngredientJsonld
     */
    'ingredientId'?: number;
    /**
     * 
     * @type {string}
     * @memberof RecipeIngredientJsonld
     */
    'ingredient'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecipeIngredientJsonld
     */
    'recipe'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecipeIngredientJsonld
     */
    'amount'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeIngredientJsonld
     */
    'unit'?: string;
}

