/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Images } from './images';
import { RecipeIngredient } from './recipe-ingredient';

/**
 * Recipes
 * @export
 * @interface Recipes
 */
export interface Recipes {
    /**
     * 
     * @type {number}
     * @memberof Recipes
     */
    'recipeId'?: number;
    /**
     * 
     * @type {string}
     * @memberof Recipes
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Recipes
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof Recipes
     */
    'servings'?: number;
    /**
     * 
     * @type {string}
     * @memberof Recipes
     */
    'source'?: string;
    /**
     * 
     * @type {number}
     * @memberof Recipes
     */
    'rating'?: number;
    /**
     * 
     * @type {number}
     * @memberof Recipes
     */
    'timesCooked'?: number;
    /**
     * 
     * @type {string}
     * @memberof Recipes
     */
    'dateAdded'?: string;
    /**
     * 
     * @type {Array<Images>}
     * @memberof Recipes
     */
    'image'?: Array<Images>;
    /**
     * 
     * @type {Array<RecipeIngredient>}
     * @memberof Recipes
     */
    'recipeIngredients'?: Array<RecipeIngredient>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Recipes
     */
    'tag'?: Array<string>;
}

