/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RecipeIngredient
 */
export interface RecipeIngredient {
    /**
     * 
     * @type {number}
     * @memberof RecipeIngredient
     */
    'recipeIngredientId'?: number;
    /**
     * 
     * @type {number}
     * @memberof RecipeIngredient
     */
    'position'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof RecipeIngredient
     */
    'quantity'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecipeIngredient
     */
    'unit'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecipeIngredient
     */
    'ingredient'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecipeIngredient
     */
    'recipe'?: string | null;
}

