/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SeasonalityScore
 */
export interface SeasonalityScore {
    /**
     * 
     * @type {number}
     * @memberof SeasonalityScore
     */
    'seasonalityScoreId'?: number;
    /**
     * 
     * @type {number}
     * @memberof SeasonalityScore
     */
    'month'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof SeasonalityScore
     */
    'score'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SeasonalityScore
     */
    'recipe'?: string | null;
}

