/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Cookup
 * @export
 * @interface ShoppingItem
 */
export interface ShoppingItem {
    /**
     * 
     * @type {number}
     * @memberof ShoppingItem
     */
    'shoppingItemId'?: number;
    /**
     * 
     * @type {string}
     * @memberof ShoppingItem
     */
    'user'?: string;
    /**
     * 
     * @type {string}
     * @memberof ShoppingItem
     */
    'ingredient'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShoppingItem
     */
    'unit'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShoppingItem
     */
    'quantity'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ShoppingItem
     */
    'done'?: boolean;
}

