/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Cookup
 * @export
 * @interface ShoppingItemJsonld
 */
export interface ShoppingItemJsonld {
    /**
     * 
     * @type {string | any}
     * @memberof ShoppingItemJsonld
     */
    '@context'?: string | any;
    /**
     * 
     * @type {string}
     * @memberof ShoppingItemJsonld
     */
    '@id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ShoppingItemJsonld
     */
    '@type'?: string;
    /**
     * 
     * @type {number}
     * @memberof ShoppingItemJsonld
     */
    'shoppingItemId'?: number;
    /**
     * 
     * @type {string}
     * @memberof ShoppingItemJsonld
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ShoppingItemJsonld
     */
    'user'?: string;
    /**
     * 
     * @type {string}
     * @memberof ShoppingItemJsonld
     */
    'ingredient'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShoppingItemJsonld
     */
    'unit'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShoppingItemJsonld
     */
    'quantity'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ShoppingItemJsonld
     */
    'done'?: boolean;
}

