/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserJsonldRead
 */
export interface UserJsonldRead {
    /**
     * 
     * @type {string | any}
     * @memberof UserJsonldRead
     */
    '@context'?: string | any;
    /**
     * 
     * @type {string}
     * @memberof UserJsonldRead
     */
    '@id'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserJsonldRead
     */
    '@type'?: string;
    /**
     * 
     * @type {number}
     * @memberof UserJsonldRead
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof UserJsonldRead
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserJsonldRead
     */
    'displayname'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserJsonldRead
     */
    'roles'?: Array<string>;
}

