/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * UserRecipeFavourites
 * @export
 * @interface UserRecipeFavourites
 */
export interface UserRecipeFavourites {
    /**
     * 
     * @type {number}
     * @memberof UserRecipeFavourites
     */
    'userRecipeFavouriteId'?: number;
    /**
     * 
     * @type {string}
     * @memberof UserRecipeFavourites
     */
    'user'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserRecipeFavourites
     */
    'recipe'?: string | null;
}

